apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
  - port: 30001
    nodePort: 30001
    protocol: TCP
    targetPort: 8001
  selector:
    app: gateway
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/fy026/weather-gateway:v3
        ports:
        - containerPort: 8001