apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-service
  name: test-service
spec:
  ports:
  - port: 30011
    protocol: TCP
    targetPort: 30011
  selector:
    app: test-service
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-service-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: registry.cn-hangzhou.aliyuncs.com/fy026/weather-service:v1
        ports:
        - containerPort: 30011